/*
 * BOARD_TASK TYPES
 */
export const GET_ERRORS = "GET_ERRORS"
export const GET_BOARD_TASKS = "GET_BOARD_TASKS"
export const GET_BOARD_TASK = "GET_BOARD_TASK"
export const DELETE_BOARD_TASK = "DELETE_BOARD_TASK"
export const GET_BOARD_PAGING = "GET_BOARD_PAGING"