/*
 * UNIVERSITY TYPES
 */
// export const 
export const GET_PUGJJIG = "GET_PUGJJIG";
export const GET_PUGJJIG_VIEW = "GET_PUGJJIG_VIEW";
export const GET_PUGJJIG_VIEW_LIKE = "GET_PUGJJIG_VIEW_LIKE";
export const GET_PUGJJIG_VIEW_LIKE_STATE = "GET_PUGJJIG_VIEW_LIKE_STATE";
export const GET_PUGJJIG_COUNT = "GET_PUGJJIG_COUNT";

/*
 * BOARD_TASK TYPES
 */
export const GET_ERRORS = "GET_ERRORS";
export const GET_BOARD_TASKS = "GET_BOARD_TASKS";
export const GET_BOARD_TASK = "GET_BOARD_TASK";
export const DELETE_BOARD_TASK = "DELETE_BOARD_TASK";
export const GET_BOARD_PAGING = "GET_BOARD_PAGING";

/*
 * USER_TASK TYPES
 */
export const CHECK_USER = "CHECK_USER";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAILURE = "CHECK_USER_FAILURE";