/*
 * UNIVERSITY TYPES
 */
export const GET_PUGJJIG_LIST = "GET_PUGJJIG_LIST";
export const GET_PUGJJIG_STORE_LIST = "GET_PUGJJIG_STORE_LIST";
export const GET_PUGJJIG_LIKE = "GET_PUGJJIG_LIKE";
export const GET_PUGJJIG_VIEW = "GET_PUGJJIG_VIEW";
export const GET_PUGJJIG_COUNT = "GET_PUGJJIG_COUNT";

/*
 * BOARD_TASK TYPES
 */
export const GET_BOARD_TASKS = "GET_BOARD_TASKS";
export const GET_BOARD_TASK = "GET_BOARD_TASK";
export const DELETE_BOARD_TASK = "DELETE_BOARD_TASK";
export const GET_BOARD_PAGING = "GET_BOARD_PAGING";

/*
 * ACCOUNT TYPES
 */
export const ACCOUNT_CREATE = "ACCOUNT_CREATE";

export const CHECK_USER = "CHECK_USER";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAILURE = "CHECK_USER_FAILURE";

/*
 * ERRORS TYPES
 */
export const GET_ERRORS = "GET_ERRORS";