/*
 * UNIVERSITY TYPES
 */
// export const 

/*
 * BOARD_TASK TYPES
 */
export const GET_ERRORS = "GET_ERRORS"
export const GET_BOARD_TASKS = "GET_BOARD_TASKS"
export const GET_BOARD_TASK = "GET_BOARD_TASK"
export const DELETE_BOARD_TASK = "DELETE_BOARD_TASK"
export const GET_BOARD_PAGING = "GET_BOARD_PAGING"

/*
 * USER_TASK TYPES
 */
export const CHECK_USER = "CHECK_USER";
export const CHECK_USER_SUCCESS = "CHECK_USER_SUCCESS";
export const CHECK_USER_FAILURE = "CHECK_USER_FAILURE";